version: '3.8'

services:
  neon-local:
    image: neondatabase/neon_local:latest
    container_name: devops-neon-local
    ports:
      - '5432:5432'
    env_file:
      - .env.development
    volumes:
      - ./.neon_local/:/tmp/.neon_local
      - ./.git/HEAD:/tmp/.git/HEAD:ro,consistent
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U neon -d devops -h localhost -p 5432']
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s
    networks:
      - devops-dev

  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: devops-app-dev
    ports:
      - '${PORT:-3000}:3000'
    env_file:
      - .env.development
    volumes:
      - .:/app
      - /app/node_modules
      - ./logs:/app/logs
    depends_on:
      neon-local:
        condition: service_healthy
    networks:
      - devops-dev
    restart: unless-stopped

networks:
  devops-dev:
    driver: bridge
